services:
    prometee.sylius_vies_client_plugin.applicator.order_european_vatnumber_applicator:
        class: Prometee\SyliusVIESClientPlugin\Applicator\OrderEuropeanVATNumberApplicator
        arguments:
            $adjustmentFactory: "@sylius.factory.adjustment"
            $zoneMatcher: "@sylius.zone_matcher"
